services:
  redis:
    image: redis:7-alpine
    container_name: gossip-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    image: gossip-chat-app
    container_name: gossip-app1
    ports:
      - "5000:80" # maps nginx inside container to localhost:5000
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    volumes:
      - .:/app
      - /app/node_modules

  app2:
    build:
      context: .
    image: gossip-chat-app
    container_name: gossip-app2
    ports:
      - "5001:80" # maps nginx inside container to localhost:5001
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5001
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    container_name: gossip-nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - app2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: nginx -g 'daemon off;'
    restart: unless-stopped

volumes:
  redis_data:
